split bootstrap into scripts

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,75 +1,27 @@
-#!/bin/sh
-set -e -o pipefail
+#!/bin/bash
 
-dir_exists () {
-  return $(test -d "$1")
-}
+# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
+# execute all executable files (excluding templates and editor backups) in the
+# ~/.config/yadm/bootstrap.d directory when run.
 
-file_exists () {
-  return $(test -f "$1")
-}
+set -eu -o pipefail
 
-DIR=$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
-if ! dir_exists "$DIR" ; then
-    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
+# Directory to look for bootstrap executables in
+BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
+
+source funcs
+
+if [[ ! -d "$BOOTSTRAP_D" ]]; then
+    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+    exit 1
 fi
 
-# brew
-echo "installing brew"
-sh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
-
-# docker
-echo "installing docker"
-sudo dnf -y install dnf-plugins-core
-
-sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
-
-sudo dnf install -y docker-ce docker-ce-cli containerd.io
-
-sudo systemctl start docker
-sudo usermod -aG docker $USER
-# newgrp docker
-# sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
-# sudo chmod g+rwx "$HOME/.docker" -R
-# sudo systemctl enable docker.service
-# sudo systemctl enable containerd.service
-
-# docker compose
-echo "installing docker compose"
-sudo dnf install docker-compose-plugin
-
-sudo curl -fL https://github.com/docker/compose-switch/releases/latest/download/docker-compose-linux-amd64 -o /usr/local/bin/compose-switch
-sudo chmod +x /usr/local/bin/compose-switch
-sudo update-alternatives --install /usr/local/bin/docker-compose docker-compose /usr/local/bin/compose-switch 99
-
-# kubernetes
-brew install kubectl
-brew install helm
-
-# misc
-sudo dnf install the_silver_searcher
-
-# vscode
-echo "installing vscode"
-sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
-sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
-
-sudo dnf install code
-code --install-extension njpwerner.autodocstring
-code --install-extension GitHub.copilot
-code --install-extension ms-python.python
-code --install-extension ms-python.vscode-pylance
-code --install-extension VisualStudioExptTeam.vscodeintellicode
-
-# post install steps
-chsh -s $(which zsh)
-
-# python build dependencies
-sudo dnf install dnf-plugins-core
-sudo dnf builddep python3
-sudo dnf install openssl1.1-1:1.1.1n-1.fc36.x86_64
-
-brew install pyenv
-pyenv install -v 3.10.3
-pyenv global 3.10.3
+find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
+    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
+        echo "Running $bootstrap"
+        if ! "$bootstrap"; then
+            echo "Error: bootstrap '$bootstrap' failed" >&2
+            exit 1
+        fi
+    fi
+done
